welcome_script_in_parallel:
  runs-on: ubuntu-latest
  steps:
    - name: Welcome part
      run: echo "Hello, guys ğŸ˜ 4444"
    - name: Get info
      run: |
        echo "Getting comp info ..."
        whoami
        sleep 17
        pwd

checks_needed:
  needs: [welcome_script, welcome_script_in_parallel]
  runs-on: ubuntu-latest
  steps:
    - name: Welcome part dependency
      run: echo "Hello, guys ğŸ˜ âœ